### ISSUE TITLE
Support addition, retrieval and removal of m2n-correspondences in reactions

### ISSUE THREAD

**Issue by max-kramer** [vitruv-tools/Vitruv#131]
Support m2n-correspondences in reactions. They are needed e.g. to realize m2n-mappings as in the addresses-recipients demo and are already internally supported but currently partially emulated using tags.

**Comment by jGleitz** [comment]
As I see it, `m:n` is already fully supported for fixed `m` and `n` using tags.

What’s not supported is `*:n` or `*:*`. I have a use case for these cases, too. From my point of view, those could be tackled by introducing a `many` keyword for correspondence retrieval: 
```
val x = retrieve many y corresponding to z (tagged with a)?
```

which would return a list with all such correspondences. With this, `*:n` would be supported. 

Additionally, one could add type restrictions on correspondences (instead of instance restrictrions), e.g. like this

```
val x = retrieve (many)? y corresponding to instanceof z (tagged with a)?
```

wher `z` would be a Metaclass reference. With this, `*:*` could be realised.

As @max-kramer said, both cases are already supported by the API.

**Comment by HeikoKlare** [comment]
The many retrieval is already discussed in #36 and will be implemented like proposed by you soon.
Nevertheless, many retrievals only solve half the problem, because they also have to be created. Many retrievals are not necessarily used for retrieving 1:n correspondences but also for retrieving multiple 1:1 correspondences.

Regarding *:* correspondences: We first need a use case that show the requirement for such a feature. From my (naive) point of view, such a correspondence should never be necessary, but a concrete use case may convince me of the contrary.

**Comment by jGleitz** [comment]
> Nevertheless, many retrievals only solve half the problem, because they also have to be created Many retrievals are not necessarily used for retrieving 1:n correspondences but also for retrieving multiple 1:1 correspondences.

I’m not quite sure what the difference between a `1:n` correspondence and many `1:1` correspondences with an equal element on one side should be. I actually only thought about the latter case. The advantage is that you can add many `1:1` correspondences without any additional syntax.

Regarding `*:*` correspondences, I have a use case were I’d like to get all correspondences with one type on one side and another type on the other side. But as I’m using the reactions to generate code and not in a “natural” way, that may be a bad example. I get your point that you first want to have a vialid use case.

**Comment by HeikoKlare** [comment]
I would be very interested in that case in which `*:*` correspondences are needed, as you mention.

My current point of view is the following: Consistency bases on consistency rules that define (on metamodel level) patterns for consistency on model level. My initial opinion was that instantiations of those patterns generally consist of a static number of elements and all cases in which a dynamic number of elements is involved can be reduced to multiple instantiations of the same consistency rule. 
We found out that there are patterns, in whose instances a dynamic number of elements is involved. For example, there is a common example with a families and a persons metamodel, in whose instances a family can correspond to a dynamic number of persons. This insight introduced the requirement for ` 1:n` correspondences.
Nevertheless, I do not yet have an example in which `*:*` correspondences are needed, so I would be very interested in that if it really exists and cannot be reduced to multiple instantiations of the same consistency rule, processed by multiple Reactions or Reactions calls.

To also mention the last kind of correspondences: `m:n` correspondences are only syntactic sugar for tagged 1:n correspondences.

**Comment by jGleitz** [comment]
What I had in mind when writing about needing `*:*` correspondences was something similar to the „stage“ or candidate list @max-kramer uses for the mappings. But that is not an actual use case because

* it would use correspondences for something entirely technical. The correspondences would not be correspondences in their actual semantics but just be a way to persist pointers
* I’m not even sure if implementing it this way makes that much sense
* It can already be achieved with the current `master`

**Comment by HeikoKlare** [comment]
I do not see that there is anything concrete left to fix or implement to "solve" this issue.
All but `*:*` correspondences can be achieved, as we have already discussed. `*:*` correspondences are conceptually not necessary but only for technical reasons like the lookup you mentioned. In my opinion, this is something language specific and should be achieved by the language implementation (e.g. using an own type of correspondence).

I would propose to close this issue, unless there are reasons or votes against it.

**Comment by jGleitz** [comment]
I agree completely.

**Comment by HeikoKlare** [comment]
Thanks for you reply, @jGleitz! :-)
