### ISSUE TITLE
UUID Resolving is Incompatible with Resources Using UUIDs

### ISSUE THREAD

**Issue by jGleitz** [vitruv-tools/Vitruv#407]
The current UUID resolving algorithm is incompatible to EMF resources using UUIDs to identify model elements (like it is implemented, for example, by the often-inherited `XMLResourceImpl`). This bug makes the UML domain incompatible.

To clear up the language, I will refer to UUIDs assigned by the resource as ‘object-UUIDs’, and refer to UUIDs assigned by Vitruv as ‘Vitruv-UUIDs’.

The gist of the problem is that object-UUIDs are _not_ an attribute of the model objects, but rather assigned by and stored in the resource. After an object is created in a view, change resolving will create its ‘mirror object’ in the VSUM. Since this ‘mirror object’ is in a different resource, it will get a different object-UUID. This works fine initially because both the normal object and the mirror object have the same Vitruv-UUID.  However, as soon as we re-load the resource in the test view, things break: We will try to query the Vitruv-UUID from the VSUM using the object’s URI. But the object’s URI contains the object-UUID, which is different in the view (and on the disk) from what the VSUM knows. Hence, we won’t find the ‘mirror object’ in the VSUM’s UUID resolver, and thus we also won’t find the Vitruv-UUID for the model object.

With this understanding, I see three feasible solutions for this problem:

 1. Allow domains to change the Vitruv-UUID resolving algorithm (c.f. #326). Domains using object-UUIDs could simply ensure that the object-UUID always equals the Vitruv-UUID. This would also simplify (and fasten) the Vitruv-UUID resolving algorithm for such domains.
 2. Disable object-UUIDs for all domains. This has two drawbacks: a) we don’t support a common feature of EMF, b) we force those domains to rely on (potentially much slower) hierarchy-based URIs instead of object-UUID-beased URIs. This workaround [has already been used at some point in the past](https://github.com/vitruv-tools/Vitruv-Domains-ComponentBasedSystems/blob/master/bundles/tools.vitruv.domains.uml/src/org/eclipse/uml2/uml/internal/resource/UMLResourceImplWithoutUUIDs.java).
 3. Adapt `UuidGeneratorAndResolverImpl` to use different URIs. We currently use `EMFUtil#getUri`, which will use the most appropriate URI (using object-UUIDs if applicable). We could instead always use hierarchy-based URIs, based on `InternalEObject#eURIFragmentSegment`, similar to what’s implemented in `ResourceImpl#getURIFragment`. My understanding is that we only fall back to URIs in `UuidGeneratorAndResolverImpl#loadUuidsToChild`. This is called when loading a fresh (unmodified) resource, so hierarchy-based URIs _should_ always work. Compared to solution 2, the performance impact is much lower, because hierarchy-based URIs are only used in `UuidGeneratorAndResolverImpl` and only when loading resources. This is better than using hierarchy-based URIs for all operations.

Solution 1 is the most holistic one and includes a nice potential performance improvement. It is also the most laborious. Solution 2 is mostly a hack. It is probably the fasted way to get rid of the problem, but it’s not _really_ a solution. It only hides the problem. Solution 3’s feasibility is not entirely clear to me. I _think_ it might work out fine, but it may also fail for some undiscovered complication. Solution 3 should be easier and faster to implement than solution 1.

Here is a test case reproducing the problem for the UML domain: https://github.com/vitruv-tools/Vitruv-Domains-ComponentBasedSystems/pull/84

**Comment by jGleitz** [comment]
Some more observations:

- This problem is specific for the situation that we reload resources in the views (hence losing the reference in the Vitruv-UUID resolver map) while not reloading in the VSUM (otherwise we would load consistent object-UUIDs
- This problem is therefore an artefact of the current state of resource handling. Once resource handling for views and the VSUM has been ‘done right’, this problem will most likely never occur.
- Nevertheless, it's noteworthy that we can game different object-UUIDs in the VSUM and the views. As long as we have different resource sets and mirror objects between them, this will persists. I think it's an issue in its own right.

**Comment by HeikoKlare** [comment]
This issue kind of surprises me because of two reasons. First, I thought that the use of XMI IDs is discouraged and that UML is the only metamodel that actually uses it for persistence, but I am not able to find this information anymore and there is no documentation in the `XMLResource` implementation stating that the UUIDs shall be removed or are discouraged to be used. Second, I thought that since UML is the only domain using these XMI IDs, disabling UUIDs in the domain would solve the problem. But the [workaround ](https://github.com/vitruv-tools/Vitruv-Domains-ComponentBasedSystems/blob/master/bundles/tools.vitruv.domains.uml/src/org/eclipse/uml2/uml/internal/resource/UMLResourceImplWithoutUUIDs.java) was actually only supposed to solve a problem with comparing UML resources, as two resources are inherently different when IDs are created anew on every save, but not to solve problems with our `UuidGeneratorAndResolverImpl`, because at the time we implemented the workaround the `UuidGeneratorAndResolverImpl` was not implemented at all. I think that because of that workaround no problems with our UUID mechanism occurred yet.

> This problem is therefore an artefact of the current state of resource handling. Once resource handling for views and the VSUM has been ‘done right’, this problem will most likely never occur.

Maybe I do not completely understand the problem, but I would expect it to remain even if resource handling for views is done properly. The view resource will still be a different instance than the resource of the same model in the `VirtualModel`. Thus, loading UUIDs to the resolver of the view will already fail, because the URIs of the same object in the `VirtualModel` resource set and the view resource set will not match. I have to admit that I do not know in detail how/when these XMI IDs are assigned, so maybe the case that two instances of the same model have different IDs will not occur in our usage scenarios.

Still, I think that it makes sense to implement one of the solutions and, in my opinion, Solution 3 is the most appropriate one. Solution 1, as far as I understand, would need to adapt the mechanism to determe the XMI IDs (object-UUIDs). I would, however, prefer a solution that adapts the Vitruv behavior to what is given by EMF resources rather than the other way round. At least, the solution should be easy to test, as already proposed in #409, so we can at least give it a try.

**Comment by jGleitz** [comment]
> I think that because of that workaround no problems with our UUID mechanism occurred yet.

I don’t think so, because I don’t see `UMLResourceImplWithoutUUIDs` being used anywhere. Instead, I think the problem newer occurred to anybody because no one tried to reload resources in the view. But I am not sure.

> Solution 1, as far as I understand, would need to adapt the mechanism to determe the XMI IDs (object-UUIDs)

Yes, I also think so. We would need to make sure that the Vitruv UUID (which is equal to the XMI ID in the view) will also be used as the XMI ID in the VSUM.

**Comment by HeikoKlare** [comment]
>I don’t think so, because I don’t see UMLResourceImplWithoutUUIDs being used anywhere. Instead, I think the problem newer occurred to anybody because no one tried to reload resources in the view. But I am not sure.

Whenever the `UmlDomain` is used, the `UMLResourceImplWithoutUUIDs` should be used, because the [`Activator`](https://github.com/vitruv-tools/Vitruv-Domains-ComponentBasedSystems/blob/master/bundles/tools.vitruv.domains.uml/src/tools/vitruv/domains/uml/Activator.java) of the project registers the according resource factory for the `.uml` file extension. But maybe I am wrong and it does not work as intended.

>Yes, I also think so. We would need to make sure that the Vitruv UUID (which is equal to the XMI ID in the view) will also be used as the XMI ID in the VSUM.

Perfect, than we agree in this regard. I will try to check the proposed PR for Solution 3 as soon as possible.

**Comment by jGleitz** [comment]
>  because the Activator of the project registers the according resource factory for the .uml file extension.

Ah, I missed that part. I checked in my tests, and it doesn’t happen there (because they don’t run in Eclipse and EMF won’t execute Activators, but only evaluate extensions).

So you are probably right: This never arose because tests (manual and automatic) were always run in Eclipse where the hack is applied.

We might check whether we still need that hack after this issue is fixed.
