### ISSUE TITLE
Correspondence not removed after cascade deletion by container

### ISSUE THREAD

**Issue by JanWittler** [vitruv-tools/Vitruv#425]
When an object is deleted as part of the deletion of its container, its correspondences are not removed.

To illustrate this, take the example of the [UmlToJavaClassMethodTest#testDeleteMethod](https://github.com/vitruv-tools/Vitruv-Applications-ComponentBasedSystems/blob/3f45c1008d9a62daede4ca5d36e7abe3362f7155/tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaClassMethodTest.xtend#L111). There, an UML operation with one parameter is deleted. Each the operation and the parameter have a correspondence to a java method / parameter. After the UML operation is deleted, the operation correspondence is removed. However, the parameter correspondence still exists (in [vsum]/correspondence/Correspondences.correspondence) even though the parameter does not exist anymore.

**Comment by HeikoKlare** [comment]
I propose the following solution:
We perform an automated cleanup of the correspondence model (potentially during save), which removes all correspondences that relate elements that have all been removed from the models. That covers the case that complete element trees have been removed with their contained elements (like the mentioned parameters of operations).
In case there are correspondences of which only some elements have been removed from the resources but others still exist, I would consider that as an indicator for a potential mistake, because potentially the corresponding elements have not been removed by mistake. Since we only use 1:1 correspondences, this means that one element has been removed but the corresponding element still exists in the models. Thus, I would propose to log a warning or even error in that case (or should we even throw an exception as the behavior is unintended?), such that the related transformation can be fixed accordingly.

I made a prototypical implementation and if am not mistaken, most dangling correspondences are properly removed. Only in very rare cases a warning is logged, because actually a correspondence was not removed properly. I will propose this in a pull request, such that we can better figure out its consequences and merge it in case we agree that it solves the mentioned problem.
