### ISSUE TITLE
GitHub Actions Check for Validation Against Applications

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#427]
I just want to paste a tought and would be interested in your opinions.
We know that large parts of the framework are not tested (well) and that we have to run our CBS applications to implicitly test framework changes. We should, of course, add (unit/integration) tests for the framework, at least for regression when fixing bugs. We will, however, not be able to provide sophisticated tests that make validation against the CBS applications obsolete soon.

Currently, I execute the CBS applications against framework changes locally. This requires building the framework and the applications (and potentially the domains) against the local updatesite generated by the framework build. This is cumbersome and slows down the development process due to manual effort and usage of local system resources for that validation.
This process is something we could also provide as an additional GitHub Actions check for the framework. We could also agree on a naming convention for branches of the domains and applications projects that adapt to changes of the framework to test them all together.

Although I know that this will neither replace proper framework tests nor be pretty efficient (such a check will potentially run for more than half an hour), I think it could improve feedback for changes.
As mentioned before, I would be interested in your opinions.

**Comment by jGleitz** [comment]
It’s funny, I had the exact same thought process the other day.

I am generally in favour because this will improve the development process and, likely, also the software quality.

_However_, I think there should be a clear understanding that:

 * This is only an interim solution
 * Vitruv needs a lot more unit tests. This is the only way that allows future developers to continue developing the framework. Without unit tests, the fear and actual risk of breaking something are too high. The current process was fine while only playground examples were built on Vitruv. Now that we have full applications being developed independently, that no longer works.
 * We should reevaluate whether we should break up the framework (e.g. externalize the languages).

See, my fear is that validating against the applications will lead to less unit testing because it relieves the immediate pressure. If we can make sure that this does not happen, I think the proposal makes sense.

>  We could also agree on a naming convention for branches of the domains and applications projects that adapt to changes of the framework

That would be essential. I think simply using the same name would be sufficient.

**Comment by HeikoKlare** [comment]
Thanks for the response! It's nice to hear that you had the same thought and agree to the idea.

> See, my fear is that validating against the applications will lead to less unit testing because it relieves the immediate pressure.

I totally understand that. However, we do the validation against applications anyway (manually) and it's only the effort that is reduced. Of course, this can lead to developers providing fewer tests because (they think) the applications tests "cover everything" anyway. But from my point of view this is a general problem in the developer's minds and our general development mindset. Since we have not properly provided unit tests for the last years (when we already had a bunch of applications that we had to keep working), I would not expect this to change on its own, no matter whether we automate application test execution upon framework changes or not. We simply have to enforce this with a proper mindset and a proper process.

While I agree to all points you made, I am not sure about breaking up the framework. I have also thought about externalizing the languages several times, but I am still not sure whether the benefits outweigh the drawbacks. The build time will decrease, but we have to manage more projects, more updatesites, perform more dependent releases and so on. But I see the arguments for either way and would, conceptually, be in favor of externalizing the languages, as the framework is meaningful even without the languages. However, this is something we can consider and discuss indepedent from the integration of an application tests check.

**Comment by jGleitz** [comment]
I agree with everything you wrote.
