### ISSUE TITLE
Use Guice Instead of ReactionBuilderFactory

### ISSUE THREAD

**Issue by jGleitz** [vitruv-tools/Vitruv#99]
`ReactionBuilderFactory` is used to abstract away form the `IReactionBuilder` implementation, which makes much sense. Nevertheless, clients could also just have a `Provider<IReactionBuilder>` injected by Guice. From my point of view, this would have the advantage that it 

a) fits better to “the way things work” in Xtext
b) allows `ReactionBuilder` to start using Guice injection without breaking clients

What’s your opinion on this?

**Comment by HeikoKlare** [comment]
Since you introduced the `FluentReactionBuilder`, we can potentially just remove the old `IReactionBuilder` and everything related to it, can't we?
This would also make the necessity to use Guid for it obsolete, or am I missing somethin?

**Comment by jGleitz** [comment]
That's correct. We should remember to remove the `SimpleTextXBlockExpression` when removing the `ReactionBuilder`.

**Comment by HeikoKlare** [comment]
I have removed the old builder (and updated everything that depended on it to the fluent builder).

The `SimpleTextXBlockExpression` is now marked as deprecated. I did not remove it yet, because the Reactions generator still supports using it (which can sometimes be more convenient than programatically creating an `XExpression`). Nevertheless, creaing a correct ´XExpression` should definitely be the preferred way.
